rails-homework/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "main#index"
  resources :physicians
  resources :patients
  resources :appointments
  resources :diagnosis_items
end

rails-homework/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is_admin?
      can :manage, :all
    else
      can :read, :all
      cannot :manage, DiagnosisItem
    end
  end
end

rails-homework/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-homework/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

rails-homework/app/models/diagnosis_item.rb
class DiagnosisItem < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

rails-homework/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :physicians, through: :appointments
  has_many :diagnosis_items

  validates_each :first_name, :last_name do |record, attr, value|
    record.errors.add(attr, "must start with upper case") if value =~ /\A[[:lower:]]/
  end

  validates :first_name, presence: true, length: { minimum: 2, too_short: "%{count} characters is the minumum allowed" }
  validates :last_name, presence: true, length: { minimum: 2, too_short: "%{count} characters is the minumum allowed" }
  validates :age, presence: true, numericality: { only_integer: true, in: 1..130 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "enter valid email" }

  def full_name
    "#{first_name} #{last_name}"
  end
end

rails-homework/app/models/physician.rb
class Physician < ApplicationRecord
  LEVELS = ["junior", "middle", "senior"].freeze

  has_many :appointments
  has_many :patients, through: :appointments
  has_many :diagnosis_items

  validates_each :first_name, :last_name do |record, attr, value|
    record.errors.add(attr, "must start with upper case") if value =~ /\A[[:lower:]]/
  end

  validates :first_name, presence: true, length: { minimum: 2, too_short: "%{count} characters is the minumum allowed" }
  validates :last_name, presence: true, length: { minimum: 2, too_short: "%{count} characters is the minumum allowed" }
  validates :phone_number, presence: true, format: { with: /\A\+380\d{9}\z/, message: "enter valid UA phone number" }
  validates :level, presence: true, inclusion: { in: LEVELS }

  def full_name
    "#{first_name} #{last_name}"
  end
end

rails-homework/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails-homework/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |_exception|
    flash[:alert] = "Access denied!"
    redirect_to root_url
  end
end

rails-homework/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource

  def new
    @patients = Patient.all
    @physicians = Physician.all
  end

  def create
    if @appointment.save
      redirect_to appointment_path(@appointment)
    else
      @patients = Patient.all
      @physicians = Physician.all
      render :new
    end
  end

  def edit
    @patients = Patient.all
    @physicians = Physician.all
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to appointment_path(@appointment)
    else
      @patients = Patient.all
      @physicians = Physician.all
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end

  private

  def appointment_params
    params.require(:appointment).permit(:appointment_date, :patient_id, :physician_id)
  end
end

rails-homework/app/controllers/diagnosis_items_controller.rb
class DiagnosisItemsController < ApplicationController
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.json do
        @diagnosis_items = DiagnosisItem.where(patient_id: params[:patient_id])
        render json: @diagnosis_items
      end
      format.html
    end
  end

  def new
    @patients = Patient.all
    @physicians = Physician.all
  end

  def create
    if @diagnosis_item.save
      redirect_to diagnosis_item_path(@diagnosis_item)
    else
      @patients = Patient.all
      @physicians = Physician.all
      render :new
    end
  end

  def edit
    @patients = Patient.all
    @physicians = Physician.all
  end

  def update
    if @diagnosis_item.update(diagnosis_item_params)
      redirect_to diagnosis_item_path(@diagnosis_item)
    else
      @patients = Patient.all
      @physicians = Physician.all
      render :edit
    end
  end

  def destroy
    @diagnosis_item.destroy
    redirect_to diagnosis_items_path
  end

  private

  def diagnosis_item_params
    params.require(:diagnosis_item).permit(:content, :patient_id, :physician_id)
  end
end

rails-homework/app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authenticate_user!
end

rails-homework/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  load_and_authorize_resource

  def create
    if @patient.save
      redirect_to patient_path(@patient)
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to patient_path(@patient)
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :email, :age)
  end
end

rails-homework/app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  load_and_authorize_resource

  def create
    if @physician.save
      redirect_to physician_path(@physician)
    else
      render :new
    end
  end

  def update
    if @physician.update(physician_params)
      redirect_to physician_path(@physician)
    else
      render :edit
    end
  end

  def destroy
    @physician.destroy
    redirect_to physicians_path
  end

  private

  def physician_params
    params.require(:physician).permit(:first_name, :last_name, :phone_number, :level)
  end
end

rails-homework/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-homework/app/views/appointments/_form.html.erb
<%= simple_form_for @appointment do |form| %>
  <%= form.input :appointment_date, as: :datetime %>
  <%= form.association :patient, collection: @patients, label_method: :full_name, value_method: :id, label: "Patient", include_blank: false %>
  <%= form.association :physician, collection: @physicians, label_method: :full_name, value_method: :id, label: "Physician", include_blank: false %>
  <br>
  <%= form.button :submit, class: "btn btn-success" %>
  <p>
    <%= link_to "< Back", :back %>
  </p>
<% end %>

rails-homework/app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>
<%= render "form" %>

rails-homework/app/views/appointments/index.html.erb
<div class="table-title">
  <div class="row mt-3 pt-3">
    <div class="col-sm-10">
      <h1>All Appointments</h1>
    </div>
    <% if can? :create, @appointments %>
      <div class="col-sm-2">
        <%= link_to "New Appointment", new_appointment_path, class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>
<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Appointment Date</th>
    <th>Full Name of the Patient</th>
    <th>Full Name of the Physician</th>
    <th>
    <% if can?(:update, @appointments) || can?(:destroy, @appointments) %>
      Actions
    <% end %>
    </th>
  </tr>
  <% @appointments.each do |appointment| %>
    <tr>
      <td> <%= link_to appointment.id, appointment_path(appointment.id) %> </td>
      <td> <%= appointment.appointment_date.strftime("%d %B %Y %H:%M") %> </td>
      <td> <%= appointment.patient.full_name %> </td>
      <td> <%= appointment.physician.full_name %> </td>
      <td>
      <% if can? :update, @appointments %>
          <%= link_to "Edit", edit_appointment_path(appointment.id), class: "btn btn-outline-primary" %>
      <% end %>
      <% if can? :destroy, @appointments %>
          <%= link_to "Delete", appointment_path(appointment.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>

rails-homework/app/views/appointments/new.html.erb
<h1>Add new Appointment</h1>
<%= render "form" %>

rails-homework/app/views/appointments/show.html.erb
<div class="row g-0">
  <div class="col col-xs-4 col-sm-6 col-md-6 col-lg-4">
    <div class="p-3 border bg-light">
      <h5 class="card-header">Appointments №<%= @appointment.id %></h5>
      <div class="card-body text-dark">
        <p class="card-text"><%= @appointment.appointment_date.strftime("%d %B %Y %H:%M") %></p>
        <p class="card-text">Patient: <%= @appointment.patient.full_name %> </p>
        <p class="card-text">Physician: <%= @appointment.physician.full_name %></p>
      </div>
      <% if can? :update || :destroy, @appointment %>
        <div class="card-footer bg-transparent border-dark">
          <%= link_to "Edit", edit_appointment_path(@appointment), class: "btn btn-outline-primary" %>
          <%= link_to "Delete", appointment_path(@appointment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
    </div>
    <%= link_to "< Back", :back %> <br>
    <%= link_to "< Back to appointments", appointments_path %>
    </div>
  </div>
</div>

rails-homework/app/views/diagnosis_items/_form.html.erb
<%= simple_form_for @diagnosis_item do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.association :patient, collection: @patients, label_method: :full_name, value_method: :id, label: "Patient", include_blank: false %>
  <%= form.association :physician, collection: @physicians, label_method: :full_name, value_method: :id, label: "Physician", include_blank: false %>
  <br>
  <%= form.button :submit, class: "btn btn-success" %>
  <p>
    <%= link_to "< Back", :back %>
  </p>
<% end %>

rails-homework/app/views/diagnosis_items/edit.html.erb
<h1>Edit Diagnosis Item</h1>
<%= render "form" %>

rails-homework/app/views/diagnosis_items/index.html.erb
<div class="table-title">
  <div class="row mt-3 pt-3">
    <div class="col-sm-10">
      <h1>All Diagnosis Items</h1>
    </div>
    <div class="col-sm-2">
      <%= link_to "New Item", new_diagnosis_item_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>
<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Full Name of the Patient</th>
    <th>Full Name of the Physician</th>
    <th>Content</th>
    <th>Actions</th>
  </tr>
  <% @diagnosis_items.each do |diagnosis_item| %>
    <tr>
      <td><%= link_to diagnosis_item.id, diagnosis_item_path(diagnosis_item.id) %></td>
      <td><%= diagnosis_item.patient.full_name %></td>
      <td><%= diagnosis_item.physician.full_name %></td>
      <td><%= diagnosis_item.content %></td>
      <td>
        <%= link_to "Edit", edit_diagnosis_item_path(diagnosis_item.id), class: "btn btn-outline-primary" %>
        <%= link_to "Delete", diagnosis_item_path(diagnosis_item.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
      </td>
    </tr>
  <% end %>
</table>

rails-homework/app/views/diagnosis_items/new.html.erb
<h1>Add new Diagnosis Item</h1>
<%= render "form" %>

rails-homework/app/views/diagnosis_items/show.html.erb
<div class="row g-0">
  <div class="col col-xs-4 col-sm-6 col-md-6 col-lg-4">
    <div class="p-3 border bg-light">
      <h5 class="card-header">Patient: <%= @diagnosis_item.patient.full_name %></h5>
      <div class="card-body text-dark">
        <p class="card-text">Diagnosis Item № <%= @diagnosis_item.id %></p>
        <p class="card-text">Physician: <%= @diagnosis_item.physician.full_name %></p>
        <p class="card-text"><%= @diagnosis_item.content %></p>
      </div>
      <div class="card-footer bg-transparent border-dark">
        <%= link_to "Edit", edit_diagnosis_item_path(@diagnosis_item), class: "btn btn-outline-primary" %>
        <%= link_to "Delete", diagnosis_item_path(@diagnosis_item), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
      </div>
    </div>
    <%= link_to "< Back", :back %> <br>
    <%= link_to "< Back to diagnosis_items", diagnosis_items_path %>
    </div>
  </div>
</div>

rails-homework/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHomework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Clinicum St. Georg", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if user_signed_in? %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Physicians", physicians_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Patients", patients_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Appointments", appointments_path, class: "nav-link" %>
            </li>
            <% if can? :manage, DiagnosisItem %>
              <li class="nav-item">
                <%= link_to "Diagnosis items", diagnosis_items_path, class: "nav-link" %>
              </li>
            <% end %>
            </ul>
            <ul class="navbar-nav ms-md-auto">
              <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link"%>
              </li>
            </ul>
          </ul>
          <% else %>
            <ul class="navbar-nav ms-md-auto">
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Log In", new_user_session_path, class: "nav-link"%>
              </li>
            </ul>
          <% end %>
      </div>
    </div>
    </nav>
    <div class="container mt-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

  </body>
</html>

rails-homework/app/views/main/index.html.erb
<div class="row g-0">
  <h1>Welcome!</h1>
    <% if user_signed_in? %>
      <div class="col col-xs-4 col-sm-6 col-md-6 col-lg-4">
        <div class="card border-light mb-3">
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to "Physicians", physicians_path %>
            </h5>
          </div>
        </div>
        <div class="card border-light mb-3">
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to "Patients", patients_path %>
            </h5>
          </div>
        </div>
        <div class="card border-light mb-3">
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to "Appointments", appointments_path %>
            </h5>
          </div>
        </div>
        <% if can? :manage, DiagnosisItem %>
          <div class="card border-light mb-3">
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to "Diagnosis Items", diagnosis_items_path %>
              </h5>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="col col-xs-4 col-sm-6 col-md-6 col-lg-4">
        <div class="card border-light mb-3">
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to "Sign Up", new_user_registration_path %>
            </h5>
          </div>
        </div>
        <div class="card border-light mb-3">
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to "Log In", new_user_session_path %>
            </h5>
          </div>
        </div>
      </div>
    <% end %>
</div>

rails-homework/app/views/patients/_form.html.erb
<%= simple_form_for @patient do |form| %>
  <%= form.input :first_name %>
  <%= form.input :last_name %>
  <%= form.input :email %>
  <%= form.input :age, as: :integer, input_html: { min: 1, max: 130 } %>
  <br>
  <%= form.button :submit, class: "btn btn-success" %>
  <p>
    <%= link_to "< Back", :back %>
  </p>
<% end %>

rails-homework/app/views/patients/edit.html.erb
<h1>Edit Patient</h1>
<%= render "form" %>

rails-homework/app/views/patients/index.html.erb
<div class="table-title">
  <div class="row mt-3 pt-3">
    <div class="col-sm-10">
      <h1>All Patients</h1>
    </div>
    <% if can? :create, @patients %>
      <div class="col-sm-2">
        <%= link_to "New Patient", new_patient_path, class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>
<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Age</th>
    <th>
    <% if can?(:update, @patients) || can?(:destroy, @patients) %>
      Actions
    <% end %>
    </th>
  </tr>
  <% @patients.each do |patient| %>
    <tr>
      <td> <%= link_to patient.id, patient_path(patient.id) %> </td>
      <td> <%= patient.first_name %> </td>
      <td> <%= patient.last_name %> </td>
      <td> <%= patient.email %> </td>
      <td> <%= patient.age %> </td>
      <td class="actions">
        <% if can? :update, @patients %>
            <%= link_to "Edit", edit_patient_path(patient.id), class: "btn btn-outline-primary" %>
        <% end %>
        <% if can? :destroy, @patients %>
            <%= link_to "Delete", patient_path(patient.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
        <% end %>
        <% if can? :read, @diagnosis_items %>
          <%= link_to "Load diagnosis items", "#patient_id#{patient.id}", data: { bs_toggle: "collapse" },
                aria: { controls: "patient_id#{patient.id}", expanded: false }, class: "btn btn-outline-success collapsed load-diagnosis",
                id: "#{patient.id}" %>
        <% end %>
        <div class="collapse" id='patient_id<%= "#{patient.id}"%>'></div>
      </td>
    </tr>
  <% end %>
</table>

rails-homework/app/views/patients/new.html.erb
<h1>Add new Patient</h1>
<%= render "form" %>

rails-homework/app/views/patients/show.html.erb
<div class="row g-0">
  <div class="col col-xs-4 col-sm-6 col-md-6 col-lg-4">
    <div class="p-3 border bg-light">
      <div class="card-header">Patient №<%= @patient.id %></div>
      <div class="card-body text-dark">
        <h5 class="card-title"> <%= @patient.full_name %> </h5>
        <p class="card-text">Email: <%= @patient.email %> </p>
        <p class="card-text">Age: <%= @patient.age %></p>
      </div>
      <% if can? :update || :destroy, @patient %>
        <div class="card-footer bg-transparent border-dark">
          <%= link_to "Edit", edit_patient_path(@patient), class: "btn btn-outline-primary" %>
          <%= link_to "Delete", patient_path(@patient), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
    </div>
    <%= link_to "< Back", :back %> <br>
    <%= link_to "< Back to Patients", patients_path %>
    </div>
  </div>
</div>

rails-homework/app/views/physicians/_form.html.erb
<%= simple_form_for @physician do |form| %>
  <%= form.input :first_name %>
  <%= form.input :last_name %>
  <%= form.input :phone_number %>
  <%= form.input :level, collection: Physician::LEVELS %>
  <br>
  <%= form.button :submit, class: "btn btn-success" %>
  <p>
    <%= link_to "< Back", :back %>
  </p>
<% end %>

rails-homework/app/views/physicians/edit.html.erb
<h1>Edit Physician</h1>
<%= render "form" %>

rails-homework/app/views/physicians/index.html.erb
<div class="table-title">
  <div class="row mt-3 pt-3">
    <div class="col-sm-10">
      <h1>All Physicians</h1>
    </div>
    <% if can? :create, @physicians %>
      <div class="col-sm-2">
        <%= link_to "New Physician", new_physician_path, class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>
<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Phone Number</th>
    <th>Level</th>
    <th>
    <% if can?(:update, @physicians) || can?(:destroy, @physicians) %>
      Actions
    <% end %>
    </th>
  </tr>
  <% @physicians.each do |physician| %>
    <tr>
      <td> <%= link_to physician.id, physician_path(physician.id) %> </td>
      <td> <%= physician.first_name %> </td>
      <td> <%= physician.last_name %> </td>
      <td> <%= physician.phone_number %> </td>
      <td> <%= physician.level %> </td>
      <td>
      <% if can? :update, @physicians %>
          <%= link_to "Edit", edit_physician_path(physician.id), class: "btn btn-outline-primary" %>
      <% end %>
      <% if can? :destroy, @physicians %>
          <%= link_to "Delete", physician_path(physician.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>

rails-homework/app/views/physicians/new.html.erb
<h1>Add new Physician</h1>
<%= render "form" %>

rails-homework/app/views/physicians/show.html.erb
<div class="row g-0">
  <div class="col col-xs-4 col-sm-6 col-md-6 col-lg-4">
    <div class="p-3 border bg-light">
      <div class="card-header">Physician №<%= @physician.id %></div>
      <div class="card-body text-dark">
        <h5 class="card-title"><%= @physician.full_name %></h5>
        <p class="card-text">Phone number: <%= @physician.phone_number %></p>
        <p class="card-text">Level: <%= @physician.level %></p>
      </div>
      <% if can? :update || :destroy, @physicians %>
        <div class="card-footer bg-transparent border-dark">
          <%= link_to "Edit", edit_physician_path(@physician), class: "btn btn-outline-primary" %>
          <%= link_to "Delete", physician_path(@physician), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
    </div>
    <%= link_to "< Back", :back %> <br>
    <%= link_to "< Back to Physicians", physicians_path %>
    </div>
  </div>
</div>